export const Links = [
    { id: 1, title: 'Home', url: '/' },
    { id: 2, title: 'Our menu', url: '/menu' },
    { id: 3, title: 'Reservation', url: '/reservation' },
    { id: 4, title: 'Career', url: '/career' },
];

export const OpenHours = [
    { id: 1, days: 'Mon - Thu', time: '12.00 - 23.00' },
    { id: 2, days: 'Thu - Sun', time: '12.00 - 03.00' },
];

export const Locations = [
    {
        id: 1,
        city: 'Stockholm',
        street: 'Knäpparvägen 40',
        postalCode: '125 57',
        postalAdress: 'Älvsjö',
        latitud: 59.27402,
        longitud: 17.98064,
    },
    {
        id: 2,
        city: 'Göteborg',
        street: 'Bögatan 46',
        postalCode: '412 72',
        postalAdress: 'Göteborg',
        latitud: 57.7023492,
        longitud: 12.0140778,
    },
    {
        id: 3,
        city: 'Malmö',
        street: 'Västra kanalgatan 1',
        postalCode: '211 41',
        postalAdress: 'Malmö',
        latitud: 55.6007252,
        longitud: 13.0023531,
    },
    {
        id: 4,
        city: 'Umeå',
        street: 'Gammliavägen 3',
        postalCode: '903 42',
        postalAdress: 'Umeå',
        latitud: 63.8275847,
        longitud: 20.2876739,
    },
    {
        id: 5,
        city: 'Västerås',
        street: 'Sturegatan 13',
        postalCode: '722 13',
        postalAdress: 'Västerås',
        latitud: 59.6115401,
        longitud: 16.5464851,
    },
];

export const Pizzas = [
    {
        id: 1,
        name: 'Tuscany',
        src: 'tuscany',
        price: 12,
        ingredients: [
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
        ],
    },
    {
        id: 2,
        name: 'Salami',
        src: 'tuscany',
        price: 10,
        ingredients: ['Lorem', 'Ipsum', 'Lorem', 'Ipsum', 'Lorem', 'Ipsum'],
    },
    {
        id: 3,
        name: 'Pepperoni',
        src: 'tuscany',
        price: 14,
        ingredients: ['Lorem', 'Ipsum', 'Lorem', 'Ipsum'],
    },
    {
        id: 4,
        name: 'The Blanco',
        src: 'tuscany',
        price: 12,
        ingredients: [
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
        ],
    },
    {
        id: 5,
        name: 'Margherita',
        src: 'tuscany',
        price: 8,
        ingredients: [
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
        ],
    },
    {
        id: 6,
        name: 'Vezuvio',
        src: 'tuscany',
        price: 12,
        ingredients: [
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
        ],
    },
    {
        id: 7,
        name: 'Rocket',
        src: 'tuscany',
        price: 12,
        ingredients: [
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
        ],
    },
    {
        id: 8,
        name: 'Pesto',
        src: 'tuscany',
        price: 12,
        ingredients: [
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
        ],
    },
    {
        id: 9,
        name: 'Truffle',
        src: 'tuscany',
        price: 12,
        ingredients: [
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
            'Lorem',
            'Ipsum',
        ],
    },
];
